name: blog
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  functional_widget_annotation: ^0.5.1

  built_collection: ">=2.0.0 <5.0.0"
  built_value: ">=5.5.5 <7.0.0"
  flutter_hooks_web:
    git: https://github.com/dart-for-apps/flutter_hooks_web
  provider_web:
    git:
      url: https://github.com/dart-for-apps/provider_web
      path: packages/provider/

dev_dependencies:
  build_runner: ^1.5.0
  functional_widget: ^0.7.1
  built_value_generator: ^6.7.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
